export const RANK_SORT_ORDER = new Map([
  ["Boss", 0],
  ["Underpaw", 1],
  ["Housecat", 2],
  ["Stray", 3],
]);

export const JOB_MAX_LEVELS: Record<string, number> = {
  Paladin: 100,
  Warrior: 100,
  "Dark Knight": 100,
  Gunbreaker: 100,
  "White Mage": 100,
  Scholar: 100,
  Astrologian: 100,
  Sage: 100,
  Monk: 100,
  Dragoon: 100,
  Ninja: 100,
  Samurai: 100,
  Reaper: 100,
  Viper: 100,
  Bard: 100,
  Machinist: 100,
  Dancer: 100,
  "Black Mage": 100,
  Summoner: 100,
  "Red Mage": 100,
  Pictomancer: 100,
  "Blue Mage": 80,
  Carpenter: 100,
  Blacksmith: 100,
  Armorer: 100,
  Goldsmith: 100,
  Leatherworker: 100,
  Weaver: 100,
  Alchemist: 100,
  Culinarian: 100,
  Miner: 100,
  Botanist: 100,
  Fisher: 100,
};

export const JOB_ICON_SLUG: Record<string, string> = {
  Paladin: "paladin",
  Warrior: "warrior",
  "Dark Knight": "darkknight",
  Gunbreaker: "gunbreaker",
  "White Mage": "whitemage",
  Scholar: "scholar",
  Astrologian: "astrologian",
  Sage: "sage",
  Monk: "monk",
  Dragoon: "dragoon",
  Ninja: "ninja",
  Samurai: "samurai",
  Reaper: "reaper",
  Viper: "viper",
  Bard: "bard",
  Machinist: "machinist",
  Dancer: "dancer",
  "Black Mage": "blackmage",
  Summoner: "summoner",
  "Red Mage": "redmage",
  Pictomancer: "pictomancer",
  "Blue Mage": "bluemage",
  Carpenter: "Carpenter",
  Blacksmith: "Blacksmith",
  Armorer: "Armorer",
  Goldsmith: "Goldsmith",
  Leatherworker: "Leatherworker",
  Weaver: "Weaver",
  Alchemist: "Alchemist",
  Culinarian: "Culinarian",
  Miner: "Miner",
  Botanist: "Botanist",
  Fisher: "Fisher",
};
